services:
  mongodb:
    container_name: mongodb
    image: mongo:8.2.3-noble
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PWD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    restart: unless-stopped

  lgtm:
    container_name: lgtm
    image: grafana/otel-lgtm:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "3030:3000"
      - "4040:4040"
      - "4317:4317"
      - "4318:4318"
      - "9090:9090"
    volumes:
      - "./lgtm-data/grafana:/data/grafana:rw"
      - "./lgtm-data/prometheus:/data/prometheus:rw"
      - "./lgtm-data/loki:/data/loki:rw"
    environment:
      - GF_PATHS_DATA=/data/grafana

volumes:
  mongodb_data:
  valkey_data:
